apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: DevOps Heroes 2022 a sample Backstage app.
  links:
    - url: https://doh22-backstage-dockerapp.azurewebsites.net/
      title: Website
    - url: https://github.com/gianfragolo/backstage-as-devops
      title: Github
    - url: https://doh22-backstage-dockerapp.scm.azurewebsites.net/api/logstream
      title: Azure Log Stream
  tags:
    - backstage
    - developer-experience
    - service-catalogue
  # Example for optional annotations
  annotations:
    github.com/project-slug: gianfragolo/backstage-as-devops
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: https://github.com/gianfragolo/backstage-as-devops/tree/main/docs/adrs
spec:
  type: website
  system: process-improvement
  owner: group:platform-engineering
  lifecycle: experimental
  dependsOn: ["component:backstage-metadata"]
