site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/gianfragolo/backstage-as-devops
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Readme: 'README.md'

  - Architecture Decision Records (ADRs):
      - Overview: 'adrs/index.md'
      - ADR001 - Architecture Decision Record (ADR) log: 'adrs/adr000-template.md'
