site_name: 'Backstage'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/gianfragolo/backstage-as-devops
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - mermaid2

nav:
  - Overview:
      - Readme: 'README.md'

