app:
  title: DevOps Heroes 2022
  baseUrl: http://localhost:3000
  support:
    url: https://github.com/backstage/backstage/issues
    items: # Used by common SupportButton component
      - title: Contact Support
        icon: supportagent
        links:
          - url: https://www.linkedin.com/events/devopsheroesparma20226933040399229853696/about/
            title: Chat

organization:
  name: DevOps Heroes

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", "http:", "https:"]
    img-src: ["'self'", "data:", "https://avatars.githubusercontent.com"]
    frame-src: ["'self'", "https://devopsheroes-2022.sessionize.com"]
    #frame-ancestors: ["'self'", "https://devopsheroes-2022.sessionize.com"]
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: "*.cloud.okteto.net"
      - host: "*.sessionize.com"
  database:
    client: better-sqlite3
    connection: ":memory:"
  cache:
    store: memory

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: "local" # Alternatives - 'external'
  generator:
    runIn: "local" # Alternatives - 'local'
  publisher:
    type: "local" # Alternatives - 'googleGcs' or 'awsS3'.

auth:
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

scaffolder:
  defaultAuthor:
    name: Luca Milan # Defaults to `Scaffolder`
    email: luca.milan@gmail.com # Defaults to `scaffolder@backstage.io`
  github:
    token: ${GITHUB_TOKEN}
    visibility: public # or 'internal' or 'private'

kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: ${OKTETO_URL}
          name: okteto
          authProvider: "serviceAccount"
          skipTLSVerify: false
          skipMetricsLookup: true
          serviceAccountToken: ${OKTETO_TOKEN}
          caData: ${OKTETO_CADATA}

catalog:
  # github:
  #   mainBranches:
  #     organization: "gianfragolo"
  #     filters:
  #       branch: "main"
  #   masterBranches:
  #     organization: "gianfragolo"
  #     filters:
  #       branch: "master"
  rules:
    - allow: [User, Group, Component, System, API, Resource, Location, Domain]
  locations:
    - type: github-org
      target: https://github.com/gianfragolo
      rules:
        - allow: [Group, User]
    - type: url
      target: https://github.com/gianfragolo/backstage-as-devops/blob/main/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/domains-and-systems.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/applepay-wrapper/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/googlepay-wrapper/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/payment-service/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/acme-landing-ui/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/applepay-wrapper-docs/blob/master/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/nodejs/template.yaml
      rules:
        - allow: [template]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/documentation/template.yaml
      rules:
        - allow: [template]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/dotnet-rest-service/template.yaml
      rules:
        - allow: [template]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/dotnet-razor-webapp/template.yaml
      rules:
        - allow: [template]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/dotnet-clean-architecture/template.yaml
      rules:
        - allow: [template]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/resources/identity.yaml
      rules:
        - allow: [resource]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/resources/databases.yaml
      rules:
        - allow: [resource]

costInsights:
  engineerCost: 200000
  products:
    computeEngine:
      name: Compute Engine
      icon: compute
    cloudStorage:
      name: Cloud Storage
      icon: storage
    bigQuery:
      name: BigQuery
      icon: search
  metrics:
    DAU:
      name: Daily Active Users
      default: true
    MSC:
      name: Monthly Subscribers
