app:
  title: DevOps Heroes 2022
  baseUrl: http://localhost:3000

organization:
  name: Gianfragolo Organization Catalog

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", "http:", "https:"]
    img-src: ["'self'", 'data:', 'https://avatars.githubusercontent.com']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"
  cache:
    store: memory

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: "local" # Alternatives - 'external'
  generator:
    runIn: "local" # Alternatives - 'local'
  publisher:
    type: "local" # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

scaffolder:
  defaultAuthor:
    name: Luca Milan # Defaults to `Scaffolder`
    email: luca.milan@gmail.com # Defaults to `scaffolder@backstage.io`
  github:
    token: ${GITHUB_TOKEN}
    visibility: public # or 'internal' or 'private'

catalog:
  rules:
    - allow: [User, Group, Component, System, API, Resource, Location, Domain]
  locations:
    # Local example organizational data
    - type: github-org
      target: https://github.com/gianfragolo
      rules:
        - allow: [Group, User]
    - type: url
      target: https://github.com/gianfragolo/backstage-as-devops/blob/main/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/domains-and-systems.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/catalog-info.yaml
      rules:
        - allow: [Component]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/nodejs/template.yaml
      rules:
        - allow: [template]
    - type: url
      target: https://github.com/gianfragolo/backstage-metadata/blob/main/templates/dotnet-rest-service/template.yaml
      rules:
        - allow: [template]
        
