name: "Build and Push Image"

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*"

  workflow_dispatch:

env:
  app_dir: app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{env.app_dir}}
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - id: vars
        name: Set current Image TAG
        run: echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"

      - name: Print current Image TAG
        run: echo "${{ steps.vars.outputs.tag }}"

      # - name: Environment Printer
      #   uses: managedkaos/print-env@v1.0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: yarn build
        run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn build

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./${{env.app_dir}}
          file: ./${{env.app_dir}}/packages/backend/Dockerfile
          tags: |
            lucamilan/backstage:latest, lucamilan/backstage:${{ steps.vars.outputs.tag }}
          build-args: |
            image_version=${{ steps.vars.outputs.tag }}

      - name: Dispatch build image event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: build-image
          client-payload: '{ "tag": "${{ steps.vars.outputs.tag }}" }'
