name: 'Build and Push Image'

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*"

  workflow_dispatch:

env:
  app_dir: app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{env.app_dir}}
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - id: vars
        run: |
          if [[ ! "$GITHUB_REF" =~ refs/tags ]]; then
            echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
          else
            echo "::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)"
          fi

      - run: echo "${{ steps.vars.outputs.tag }}"

      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn tsc
        run: yarn tsc:full

      - name: yarn build
        run: yarn build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backstage image to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./${{env.app_dir}}
          file: ./${{env.app_dir}}/packages/backend/Dockerfile
          tags: |
            lucamilan/backstage:latest, lucamilan/backstage:${{ steps.vars.outputs.tag }}
          build-args: |
            image_version=${{ steps.vars.outputs.tag }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: build-image
          client-payload: '{ "tag": "${{ steps.vars.outputs.tag }}" }'